### ISSUE TITLE
Glitch resizing a div caused by simplebar

### ISSUE THREAD

**Issue by villeneuve-michael** [Grsmto/simplebar#253]
## Current Behavior

I have an application and I want to resize a div width. The application layout has 3 column: 
- 2 fixed sidebar (left and right)
- 1 main container in the middle

There is 1 of my sidebar that I want to resize (view the screecast below).

Without the plugin enabled, all is perfect. However, when I activated simplebar, there was a weird behaviour where the sidebar would expand offscreen.

## Expected behavior

I want the div the resize as expected

## Reproducible example

Since it's a pretty big app, it's easier for me to share the problem via [screencast](https://drive.google.com/file/d/18s15-yjx2KdHOqrueAxoSd8jWeUG-O7U/view)

## Suggested solution(s)

So after playing with different options, I figured out the following solution : 

```css
.simplebar-placeholder {
  display: none;
}
```

## Additional context

Since I installed the plugin today, I didn't feel confortable issuing a pull request since maybe adding display: none will break other features.

**Comment by Grsmto** [comment]
Hi Michael,
It seems like the `simplebar-placeholder` is resizing properly from what I see in your screencast, so this might "just" be a CSS issue. Hard to say without seeing the code but how are you doing the "expand/minimize"? Is it a CSS animation? What's your CSS for this animation?

**Comment by Spegeli** [comment]
I installed this scrollbar plugin and i can confirm this issue.

placeholder enabled / showen:
http://i.epvpimg.com/YNMLdab.png

placeholder disabled / hidden:
http://i.epvpimg.com/GaIhcab.png

My page is normal ~950px high but the placeholder makes it ~1500px.

**Comment by villeneuve-michael** [comment]
@Grsmto 

It's a simple transition. I toggle the expand class on my sidebar:
```scss
aside {
  flex: 0 0 auto;
  width: 260px;
  &.expand {
     width: 520px;
  }

  -webkit-transition: width .25s;
  -moz-transition: width .25s;
  -ms-transition: width .25s;
  -o-transition: width .25s;
  transition: width .25s;
}

```
