### ISSUE TITLE
Infinite recalculation loop with tiny div in Firefox

### ISSUE THREAD

**Issue by andersk** [Grsmto/simplebar#327]
**Describe the bug**
Putting a SimpleBar on a tiny div under certain circumstances results in an infinite recalculation loop in Firefox.

**To Reproduce**
Run [this jsfiddle](https://jsfiddle.net/anderskaseorg/4be5o91j/) in Firefox. It consists of

```html
<div id=outer data-simplebar>
  <div id=inner>
  </div>
</div>
```

```css
#outer {
  width: 15px;
  height: 10px;
}

#inner {
  border-right: 20px solid blue;
  height: 20px;
}
```

I see visible flashing as the SimpleBar repeatedly recalculates.

**Expected behavior**
There’s nothing dynamic here, so SimpleBar should only recalculate once.

**Reproducible example**
https://jsfiddle.net/anderskaseorg/4be5o91j/

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0
| Browser          | Firefox 66.0.5
| Operating System | Ubuntu 19.04
