### ISSUE TITLE
Properties: width, width@hover

### ISSUE THREAD

**Issue by AlexSHoffman** [Grsmto/simplebar#361]
Hi, what do you think about adding these props:

`data-simplebar-v-width` - sets width of the vertical thumb
`data-simplebar-v-width-on-hover` - sets width of the vertical thumb on hover
`data-simplebar-h-width` - sets width of the horizontal thumb
`data-simplebar-h-width-on-hover` - sets width of the horizontal thumb on hover

```HTML
<div 
  data-simplebar-v-width="5px"
  data-simplebar-v-width-on-hover="10px"
/>
```

**Comment by Grsmto** [comment]
Hi Alex,
This is defined by CSS, so the way to do that is via CSS overrides instead of using JS.
So something like:
`.simplebar-track.simplebar-vertical { width: 5px }`
`.simplebar-track.simplebar-vertical:hover { width: 10px }`

**Comment by AlexSHoffman** [comment]
@Grsmto I tried it. Here's the summary:

This works:

```CSS
.simplebar-track.simplebar-vertical { 
  width: 5px !important
}
```

But this doesn't work:

```CSS
.simplebar-track.simplebar-vertical:hover { 
  width: 10px !important
}
```
It changes with to `10px` but not on `:hover`, it works only after you click & start dragging.

**Comment by andersk** [comment]
Try `.simplebar-track.simplebar-vertical.simplebar-hover`.

**Comment by AlexSHoffman** [comment]
@andersk thank you this works!

**Comment by AlexSHoffman** [comment]
This behavior can be achieved in the following way, so the issue is resolved:

```CSS
.simplebar-track.simplebar-vertical { 
  width: 5px !important; 
}
.simplebar-track.simplebar-vertical.simplebar-hover { 
   width: 10px !important; 
   margin-right: 0px;
}
```
