### ISSUE TITLE
stylling issue

### ISSUE THREAD

**Issue by Atomization** [Grsmto/simplebar#365]
I have 2 elements within my document, 1st one is a `<main>`, 2nd is a `<div>` container

I have set the main `overflow-y: auto;` and the main is `width: 100%` and `height: 100vh;` so it covers the whole page and contains every element

The 2nd scroll `<div>` element is `overflow-x: auto` to get horizontal  scrolling, I found the scroll container class `.simplebar-content` and changed styles to format the horizontal scrolling div
```css
.simplebar-content {
  display: flex; /* to display children out horizontally */
}
```
now the 1st scroll element takes on the style I intended on applying to the 2nd scroll element
and my `<section>`'s within my main are displayed out side by side, when its supposed to be from top to bottom.

so my question being, how do I apply the styles to only the 2nd scroll element?
