### ISSUE TITLE
glitched with Firefox 63+ [scrollbar-width]

### ISSUE THREAD

**Issue by krystian3w** [Grsmto/simplebar#427]
## Describe the bug

Glitched with new:

    https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
    https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color

```css
:root {
    scrollbar-face-color: #C1C1C1; 
    scrollbar-track-color: #F1F1F1; 
  
    scrollbar-color: #C1C1C1 #F1F1F1;
  
    scrollbar-width: auto;
}

:root * {
   scrollbar-width: inherit;
}
```

![obraz](https://user-images.githubusercontent.com/35370833/71494631-d4225e80-2848-11ea-8894-2b20e25b5dec.png) |
--- |

## To Reproduce

1. Go to 'https://jsfiddle.net/fayp0zq4/'
2. See glitch on hover element - system scroll under `simplebar`

![obraz](https://user-images.githubusercontent.com/35370833/71494651-003ddf80-2849-11ea-9d7a-952853e51889.png) |
---- |

## Expected behavior

Can override `scrollbar-width`? or color: `scrollbar-color: #0000 #0000;`

## Reproducible example

https://jsfiddle.net/fayp0zq4/

## Additional context

N/A

## Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | v5.1.0
| Browser          | Firefox 71 (x64)
| npm/Yarn         |  unpkg.com
| Operating System | Windows 10 Pro (x64)
