### ISSUE TITLE
Allow maxHeight values other than px

### ISSUE THREAD

**Issue by decimoseptimo** [Grsmto/simplebar#439]
I'm trying to do a responsive harmburger menu a la youtube.com, I think i naliled, but is this approach correct?: https://codesandbox.io/s/trusting-galileo-8qk39

I was a bit hacky, i couldn't do `<SimpleBarReact style={{ maxHeight: SOME_CSS_HEIGHT_VALUE }}>`. I had to do:
```css
[data-simplebar] {
  max-height: calc(100vh - 4em) !important;
  width: 250px;
}
```

Also, i couldn't use %'s but vh units worked. What do you think?
