### ISSUE TITLE
`simplebar-placeholder` overflows the Simplebar container if it's a flex item, rendering content below it unclickable

### ISSUE THREAD

**Issue by WofWca** [Grsmto/simplebar#475]
**Describe the bug**
See reproduction

**To Reproduce**
1. Have HTML + CSS  ~ as follows:
    <details>
    
    <summary>src</summary>
    
    ```html
    <aside id=sidebar>
      <div>Header</div>
      <div id=content>
        <div>Item 1</div>
        <div>Item 2</div>
        <div>Item 3</div>
        <div>Item 4</div>
        <div>Item 5</div>
        <div>Item 6</div>
        <div>Item 7</div>
        <div>Item 8</div>
        <div>Item 9</div>
        <div>Item 10</div>
        <div>Item 11</div>
      </div>
      <div id=footer>
        Footer<br>
        <a href="example.org">Try me</a>
      </div>
    </aside>
    ```
    ```css
    #sidebar {
        height: 10em;
        width: 10vw;
        min-width: 100px;
        display: flex;
        flex-direction: column;
    }
    
    #content {
      flex-grow: 1;
      min-height: 0px; /* So it can shrink */
      /* Uncommenting the following line apparently fixes the issue. */
      /* height: 100%; */
    }
    
    #footer {
      background: gray;
    }
    ```
    </details>
2. Try to click the link in the footer.

**Expected behavior**
The link is followed

**Reproducible example**
https://jsfiddle.net/WofWca/67fyu8w5/

**Additional context**

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.2.0
| Browser          | 81.0.4044.138
| npm/Yarn         | CDN
| Operating System | Windows 10
