### ISSUE TITLE
any way to specify the cursor style or apply z-index?

### ISSUE THREAD

**Issue by scratchoo** [Grsmto/simplebar#490]
I have a sidebar menu with simplebar applied to it, the elements of sidebar has the css (cursor: pointer)

when I hover over the scrollbar the mouse still show up as pointer! 

Any way to change this?

**Comment by ux-engineer** [comment]
Tried using this CSS:

```css
.simplebar-track.simplebar-vertical.simplebar-hover {
  cursor: ns-resize;
}
```
As mentioned [here](https://github.com/Grsmto/simplebar/issues/229), it seems that hover tracking is done purely with JS and with `pointer-events: none;` CSS rule, so probably this is why the cursor rule **gets applied only when mouse button is clicked and not while hovering**...

**Comment by liesahead** [comment]
@ux-engineer , doesn't work.

**Comment by ux-engineer** [comment]
@liesahead I'm using this:

```sass
.simplebar-track.simplebar-vertical {
  width: 16px
  z-index: 9998

  &.simplebar-hover {
    cursor: ns-resize
  }
}
```

**Comment by liesahead** [comment]
@ux-engineer , thanks, however I already found a solution. For me such code works:

```css
.simplebar-track {
    cursor: default;
    pointer-events: auto;
}
```

This is just an example code, in our project we have a slightly modified layout, so the above css is set on another element.
