### ISSUE TITLE
Native scrollbar is visible under simplebar

### ISSUE THREAD

**Issue by RafalFilipek** [Grsmto/simplebar#521]
Hi

https://codesandbox.io/s/determined-joliot-bbmtb 

iOS 14, Safari & Chrome

![image](https://user-images.githubusercontent.com/80960/93499878-d74c0600-f913-11ea-8c5c-ed3ec60b90d4.png)

There is nothing special in this  example. 

http://grsmto.github.io/simplebar/ is working just fine.

Thank you

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.2.1
| Browser          | Safari / iOS Chrome
| npm/Yarn         | ?
| Operating System | iOS

**Comment by RafalFilipek** [comment]
Possible fix

```css
.simplebar-content-wrapper::-webkit-scrollbar {
  display: none;
}
```
