### ISSUE TITLE
Duplicate scrollsbar on moblie

### ISSUE THREAD

**Issue by mtr1990** [Grsmto/simplebar#533]
![7106523A-285A-4676-A5D4-6FF870B9C33D](https://user-images.githubusercontent.com/13531993/97341605-d9f92e00-18b7-11eb-86e1-88d4f69c065a.jpeg)
## 💬 

I am using chrome and safari on mobile, How can i fix it ?

**Comment by Marientus** [comment]
Have the same issue on the newest iphones on safari. The scrollbar on mobile safari is slightly animated so it can grow a bit larger on using it. Maybe you or the lib author could recommend any workarounds on this issue? :)

**Comment by zecka** [comment]
You can force hide native scrollbar like that:
```css
.simplebar-content-wrapper::-webkit-scrollbar {
    display: none;
}
```
