### ISSUE TITLE
Is it possible to set SimpleBar width based on content width?

### ISSUE THREAD

**Issue by vladimir-djokic** [Grsmto/simplebar#565]
## 💬 Questions and Help

Is it possible to set SimpleBar width based on content width, without using JavaScript to access DOM/Calculate/Update SimpleBar width? Something like (React example):

```js
<SimpleBar className="max-height-20rem width-max-content">
  <MyList />
</Simplebar>
```
```css
.max-height-20rem {
  max-height: 20rem;
}

.width-max-content {
  width: max-content; /* This obviously does not work /*
}
```

**Comment by strarsis** [comment]
+1! The legacy/deprecated jquery.scrollbar allowed the whole scroll area to grow with its content width - even allowing for CSS width transitions. It would be great if this is also possible with simplebar as I migrate to it.

**Comment by idefant** [comment]
It works for me:
```css
.simplebar-placeholder {
  width: max-content !important;
}
```
